In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import json
import os
import csv
from pprint import pprint

In [3]:
csv_file = "Merged.csv"
testing = pd.read_csv(csv_file)

In [4]:
testing.head()

,suicide_country,suicide_year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),...,Positive affect,Negative affect,Confidence in national government,Democratic Quality,Delivery Quality,Standard deviation of ladder by country-year,Standard deviation/Mean of ladder by country-year,GINI index (World Bank estimate),GINI index (World Bank estimate).1,average 2000-15
0,Albania,2007,male,75+ years,8,42366,18.88,Albania2007,NaN,1.070101e+10,...,0.552678,0.246335,0.300681,-0.045108,-0.420024,1.764947,0.380848,NaN,0.30325,NaN
1,Albania,2007,male,35-54 years,29,378626,7.66,Albania2007,NaN,1.070101e+10,...,0.552678,0.246335,0.300681,-0.045108,-0.420024,1.764947,0.380848,NaN,0.30325,NaN
2,Albania,2007,male,55-74 years,14,224160,6.25,Albania2007,NaN,1.070101e+10,...,0.552678,0.246335,0.300681,-0.045108,-0.420024,1.764947,0.380848,NaN,0.30325,NaN
3,Albania,2007,female,75+ years,3,57404,5.23,Albania2007,NaN,1.070101e+10,...,0.552678,0.246335,0.300681,-0.045108,-0.420024,1.764947,0.380848,NaN,0.30325,NaN
4,Albania,2007,male,25-34 years,9,172494,5.22,Albania2007,NaN,1.070101e+10,...,0.552678,0.246335,0.300681,-0.045108,-0.420024,1.764947,0.380848,NaN,0.30325,NaN